/**
 * Created by cheng on 2015/11/20.
 */
// var oImage=new Image();
//         oImage.onload=function(){{

//             $(".t_banner img").animate({bottom:10,opacity:1},800);
//         }
// oImage.src='http://www.mobiletrain.org/teacher/http://www.mobiletrain.org/teacher/img/teacher/banner.jpg';
$(function(){
    var arr,$baseUl,$baseLi,$proCon,$proI,$proDd;
    $baseUl=$(".teacher_list_nav ul li");
    arr=[
            [[//ad1
                 {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/zhangxiaohe.jpg",
                    dis:"display:block",
                    teacher:"张老师",
                    require:"",
                    introduction:"<span>个人简介：</span>蔻丁Android学科总监，9年多移动应用相关工作经验，国内Android开发工程师，深入了解移动应用系统，在网络协议与手机浏览器内核设计方面有丰富的经验。从事工作涉及企业办公、移动通讯等领域，为企业培养众多业务骨干。擅长总结归纳，化繁为简，化难为易，教学方法独特，富有激情，擅以理论结合实际、提高学生项目开发实战的能力。技术领域涉及广泛，曾主导定制手机浏览器内核设计、开发工作；参加移动运营声众多项目设计、实施；参与海外移动运营商移动终端软件项目设计、实施。参与多项企业级移动应用开发工作。",
                    video:""
                },

                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/diyuhuan.jpg",
                    dis:"display:block",
                    teacher:"狄老师",
                    require:"",
                    introduction:"<span>个人简介：</span>蔻丁Android学科副总监，7年多教育工作经验，3年多Android研发工作经验。2007年进入中科院西安网络中心从事J2EE教育与研发工作，2009年担任陕西省税务局软件开发培训的《软件架构设计》与《Oracle数据库管理》方面的讲师。自2010年以来，先后参与国家基金委基金项目管理系统、中科院公文平台系统、吉林省白城市工商局巡检移动终端Android手机版，并承担与部队有关的Android平板项目研发的技术主管。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/jiangqiangwei.jpg",
                    dis:"display:block",
                    teacher:"蒋老师",
                    require:"<span>讲师语录：</span>一个100行的代码调试都可能会让程序员遇到很多挫折，所以，面对挫折，我们永远不能低头！",
                    introduction:"<span>个人简介：</span>蔻丁Android学科高级讲师，丰富的JavaEE项目开发经验和Android开发经验。曾多次到大学中进行Android课程培训，参加学生项目实践课程指导，受到学生广泛的好评。对待工作认真负责，要求严格，善于总结，能够清晰把握上课知识脉络，授课思路清晰。对待学生平易近人，耐心解决学生学习中遇到的各种问题。讲解知识点全面，将授课案例贴切并且结合项目实际需求，实战性强，让学生比较容易的接受知识并且灵活运用。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/wangwujuan.jpg",
                    dis:"display:block",
                    teacher:"王老师",
                    require:"<span>讲师语录：</span>聪明出于勤奋，天才在于积累！",
                    introduction:"<span>个人简介：</span>蔻丁Android高级讲师，多年的Android项目开发经验和丰富的教学经验，掌握Android各种基础开发和高级开发的知识。曾参与一些相关sip网络通话，电话会议以及网络加速等项目的开发工作。在教学工作中认真负责，授课思路清晰，实战性强，善于总结分析，帮助学生掌握更多的技能知识，让学生快速开发出高质量的App。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/xuzhong.jpg",
                    dis:"display:block",
                    teacher:"许老师",
                    require:"<span>讲师语录：</span>零一即阴阳，万物皆对象！",
                    introduction:"<span>个人简介：</span>蔻丁教学部Android讲师，之前从事过数据库脚本、ETL算法、Java EE开发，在移动互联方兴未艾之际，投身Android开发事业，四年Android项目经验，两年多教学经验，程序人生，业余时间喜欢写代码，一款《黑白方块》游戏，深受同学们喜爱，语言幽默，描述知识生动形象，讲述知识点化繁为简，更多的结合实际开发中的例子，让同学们更好的理解并加以运用，具体教学重视编码，是一位更倾向于具体代码实现的一位讲师。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/xiexiaobo.jpg",
                    dis:"display:block",
                    teacher:"谢老师",
                    require:"<span>讲师语录：</span>不许任何人说你不行，就连自己也不允许！",
                    introduction:"<span>个人简介：</span>安卓讲师, 多年开发经验。在北京绩优堂科技有限公司工作多年，参与APP的研发。其中包括早期的智能教辅、名师辅导、错题笔记，其中参与项目的框架的搭建。早期的名师讲题融资1000多万，集合了各大名校的名师，遍布全国，其中主要是北京和河南的名师，致力打造全国最大的慕课平台。后期公司的替代产品天天向上已完全替代名师讲题。智能教辅是一款结合互联网和线下教育的一款软件，实现了教育和网络的无缝隙连接。此软件可以扫描二维码的形式，把公司的所出书上的题目，以视频讲解的方式给用户展现出来，这样使得我们公司的纸质书籍特卖大卖。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/rongjiawei.jpg",
                    dis:"display:block",
                    teacher:"荣老师（RockRong）",
                    require:"<span>讲师语录：</span>多年后你一定会感谢年轻时奋斗的自己！",
                    introduction:"<span>个人简介：</span>本人性格开朗，待人真诚，对工作有上进心，有很强的适应能力和团队精神。但是属于慢热型性格。本人喜欢研究一些新技术，经常使用gitHub阅读一些源码，并会写相关Demo进行测试，总结一些经验。曾入职互联网金融公司，了解互联网金融运转模式。在家装O2O公司，对家装O2O的产品模型有一定理解。<br />在企业中看到互联网的未来，对互联网的发展充满信心，入职蔲丁教育也是因为看到了互联网的人才缺口市场，并且对教育事业充满信心。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/liduo.jpg",
                    dis:"display:block",
                    teacher:"李老师",
                    require:"<span>讲师语录：</span>心在远方，路在脚下!脚踏实地，一步一个脚印!每天进步一点点！",
                    introduction:"<span>个人简介：</span>曾先后任职于多家大中型企业，具有丰富的项目开发经验，曾参与完成多省、市的警务综合系统的开发;曾参与某数据通信公司主要业务的设计与开发。2008年担任讲师以来，一直从事java方向的专业培训，精通web开发的各种技术;对Android体系结构有深入的理解。<br />授课特点：注重培养学生的动手能力，自我学习能力,课上风趣幽默，具有亲和力，对学生认真、耐心、负责,知识点深入浅出，结合实际开发中的应用进行讲解。",
                    video:""
                }
            ],
            [//ad2
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/chenjunbo.jpg",
                    dis:"display:block",
                    teacher:"陈老师（若寒若冰）",
                    require:"<span>讲师语录：</span>我的学生要快乐的学习,不要死气沉沉的写代码！",
                    introduction:"<span>个人简介：</span>六年IT工作经验,丰富的工作经验以及解决问题的经验,有多款应用在各大应用商店上架,善于将学习到的东西与工作相结合,讲课幽默风趣,善于主动引导学生思考,善于和学生交流,喜欢和同学玩到一起,会从多角度分析问题,解决问题,对于新技术知识有研究,会一直为学员毕业后工作提供技术支持。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/liliting.jpg",
                    dis:"display:block",
                    teacher:"李老师（小李老师）",
                    require:"<span>讲师语录：</span>多年后你一定会感谢现在努力的自己！",
                    introduction:"<span>个人简介：</span>蔻丁教学部Java讲师，多年软件开发经验，曾经参与中国人寿保险投保项目(PICC人寿保险)的开发工作，现此项目已经上线。有java培训从业经验，曾从事互联网开发相关课程的教学工作，具有丰富的教学经验，深厚的编程底蕴，有趣的学习氛围，洪亮的声音把您带入移动互联网开发的知识殿堂;授课由浅入深、生动实用，把生活案例引入到学习中，让枯燥的学习变成有趣的事，在愉快的氛围里学到了知识。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/liusihui.jpg",
                    dis:"display:block",
                    teacher:"刘老师（慧姐）",
                    require:"<span>讲师语录：</span>你脑子里东西的多寡，就关系着你将来的前途。你希望掌握永恒，那你必须控制现在！",
                    introduction:"<span>个人简介：</span>蔻丁安卓学科讲师，有4年多研发经验，参与了多个项目的开发，并且有多款应用成功发布在Android Market。具有极其丰富的设计、开发经验。有良好的表达和沟通能力，良好的心理把握能力和良好的职业素养。授课风格：思维敏捷，通俗易懂，善于运用启发和引导的方式施教，达到最好的教学效果。授课条理清晰，理论与实践紧密结合，注重学生的动手和应用能力。声音洪亮，富有激情、有亲和力。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/lirui.jpg",
                    dis:"display:block",
                    teacher:"李老师（锐姐）",
                    require:"<span>讲师语录：</span>没有努力就没有成功！",
                    introduction:"<span>个人简介：</span>蔻丁Android学科高级讲师，有多款应用发布在Android各大市场，长期从事移动端和Windows软件/网站开发，开发经验丰富。为人和善，易与学生亲近，善于引导学生培养自己思考问题和动手解决问题的能力。讲课深入浅出，简洁明了，深受广大学生的喜爱。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/zhaoxuesen.jpg",
                    dis:"display:block",
                    teacher:"赵老师",
                    require:"<span>讲师语录：</span>优秀是一种习惯！",
                    introduction:"<span>个人简介：</span>蔻丁教学部高级Android讲师，5年多移动互联网研发经验，曾参与银行、商城、智能家居等项目的开发工作。授课有着迷人的魅力，深深抓住每一个学员的心扉，而在讲解知识中，总会有出其不意的精彩亮点，深受学生们的喜爱。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/dangguotao.jpg",
                    dis:"display:block",
                    teacher:"党老师",
                    require:"<span>讲师语录：</span>一条道走到黑！",
                    introduction:"<span>个人简介：</span>拥有十年编码及架构设计经验，擅长Java后端和web前端开发。2009年进入手机app领域，在iOS和Android平台上先后参与开发期货交易客户端“随身行”、平安银行客户端“口袋银行”等应用，对App的UE、架构、数据管理等方面有独到见解。最近一年的研究方向为跨平台技术HTML5，cocos2d-x等。在教学过程中，对知识点的讲解深入浅出， 能够很好的将抽象概念转换成生活中的实例，加快学员的理解。善于培养学员独立学习和解决问题的能力，能够见缝插针地把工作多年积累的丰富开发经验悉数分享，深受学生喜爱。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/zhangshuiping.jpg",
                    dis:"display:block",
                    teacher:"张老师",
                    require:"<span>讲师语录：</span>永远用欣赏的眼光看学生，永远用宽容的心态面对学生！",
                    introduction:"<span>个人简介：</span>9年移动端开发经验，其中7年Android开发经验，也是国内首批从事Android开发的技术从业者之一，曾在华为、上海华勤等国际知名IT公司任职，主持并参与华为、联想等多款手机项目的研发，擅长手机应用层开发!<br />授课通俗易懂，将知识重点融会贯通，让学员不但学会，而且能够会学!",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/huangjinjin.jpg",
                    dis:"display:block",
                    teacher:"黄老师（金姐）",
                    require:"<span>讲师语录：</span>兴趣是最好的老师！",
                    introduction:"<span>个人简介：</span>蔻丁Android讲师，多年的Android开发经验。曾参与国家环保局环境监测、移动执法和国家公安局移动警务通等大型项目的开发。常以风趣，幽默的语言活跃课堂气氛能记住每一个学生身上的优点与喜好，与学生打成一片。激发并且引导学生对代码产生兴趣，能够让学生在兴趣中快乐的学习。授课思路清晰，以规范的教学案例及代码示范，让学生轻易掌握知识点并能灵活运用。经常通过讲述自己工作中的小故事来传授学生一些实际工作中的经验，能够让学生在学习和工作之间更好的过渡，避免环境突然变化带来的不适应。",
                    video:""
                }
            ],
            [//ad3
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/ad_prc3.jpg",
                    dis:"display:block",
                    teacher:"杨老师",
                    require:"<span>讲师语录：</span>读前人的书，欠前人的债！",
                    introduction:"<span>个人简介：</span>10年软件研发经验，8年教学经验。曾在知名IT公司任设计师、系统分析、项目经理、架构师，技术总监等职，主持并参与湖北省孝感市中心医院ERP、某大型航空企业劳动定额管理系统、长庆油田合同管理系统二期、甘肃省白银市供电局电气设备动热稳定校验系统等大中型项目的研发，擅长 Java、JavaEE、Oracle、UML、框架等技术。教学风格独道新颖而不失标准、授课气氛诙谐幽默而兼顾严谨扎实。注重学员表达能力、学习能力、沟通能力、承压能力、分析问题与解决问题能力、擅长专业文档编写能力的综合培养；使学员在获得知识的同时，不断的延展了自己的思维，真正掀起了一场学习的革命！",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/ad_prc6.jpg",
                    dis:"display:block",
                    teacher:"王老师",
                    require:"<span>讲师语录：</span>锲而不舍，金石可镂！",
                    introduction:"<span>个人简介：</span>多年Android项目研发经验，熟悉混合式开发，对AndroidFramework层代码有深入理解，对JavaEE、微信后台开发亦有深入研究，长期坚持在CSDN写博客，是CSDN博客专家。曾参与全景医疗、安泰手术室等项目研发。技术功底深厚，讲课思路清晰，深入浅出，善于引导学生自主学习，让学生不仅听得懂，更能记得住、说得出。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/ad_prc8.jpg",
                    dis:"display:block",
                    teacher:"邱老师",
                    require:"<span>讲师语录：</span>你可以这样理解impossible——I’m possible！",
                    introduction:"<span>个人简介：</span>蔲丁教育大连校区Android高级讲师，拥有多年JavaEE项目开发经验及Android开发经验。常以风趣、幽默的语言活跃课堂气氛，能记住每位学员的优点和缺点，因材施教。授课思路清晰，以贴切的教学案例及代码示范，让学生轻松掌握知识点并能够灵活应用。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/chenheng.jpg",
                    dis:"display:block",
                    teacher:"陈老师",
                    require:"<span>讲师语录：</span>兴趣是人最好的老师！",
                    introduction:"<span>个人简介：</span>蔲丁Android学科高级讲师，拥有多年的Java及Android开发及教学经验，精通Android相关各种开发基础与技巧。在企业中曾带领团队开发过多个大型移动互联网项目。对移动应用开发有着自己独到见解和丰富心得，结合自己多年的开发经验和心得将知识以通俗易懂的方式传授给学生，授课幽默风趣，注重培养学生兴趣，引导学生自己解决问题，深受学生欢迎。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/huxinyue.jpg",
                    dis:"display:block",
                    teacher:"胡老师",
                    require:"<span>讲师语录：</span>心有多大舞台就有多大！",
                    introduction:"<span>个人简介：</span>蔲丁Android讲师，4年JavaEE开发经验和Android开发经验，曾参与北京市检察院、北京市工商局、北京市旅游局等财务管理系统的开发及维护，主要负责公司内部框架的开发工作，并且开发出多款主流App，技术能力以及个人研发能力都很强。教学方面授课思路清晰，讲解详细，善于总结，深受学生认可。授课期间经常培养学生的独立思考能力，并且结合项目实例让学生熟练掌握知识点。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/huangting.jpg",
                    dis:"display:block",
                    teacher:"黄老师",
                    require:"<span>讲师语录：</span>不逼一下自己，怎么知道自己多么优秀！",
                    introduction:"<span>个人简介：</span>蔲丁Android学科高级讲师，多年的JavaEE项目开发经验、Android开发经验、Android教学经验，曾参加深圳第二十六届世界大学生运动会赛事成绩系统的开发测试运维等工作并获评优秀。对待教学认真负责，要求严格，循循善诱，平易近人，不厌其烦，细心讲解，深受学生喜爱。授课温文儒雅、注意启发和调动学生的积极性，课堂气氛较为活跃，为学员掌握开发语言到项目实战提供强有力的保障，得到学员的高度好评。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/ouyangsuo.jpg",
                    dis:"display:block",
                    teacher:"欧阳老师",
                    require:"<span>讲师语录：</span>每天都造点好玩的东西出来——这就是一个牛叉程序员的情怀!",
                    introduction:"<span>个人简介：</span>多年移动互联网开发经验，参与项目有：参与手游东方江湖手机端研发；参与家庭智能音乐播放设备睿妙影研发并担任手机遥控器端APP主程；参与股票证券APP益盟私募工厂客户端研发并担任产品经理及项目经理。对安卓应用开发、J2EE服务端开发、嵌入式及FlashAS均有一定涉猎。格言：每天都做一点好玩的东西出来，这就是一个好程序员的全部。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/tanzheng.jpg",
                    dis:"display:block",
                    teacher:"谭老师",
                    require:"<span>讲师语录：</span> 程序员在代码中总是会遇到很多难题，但我们一路披荆斩棘、勇往直前。面对挫折，我们永不低头。你，准备好了么？",
                    introduction:"<span>个人简介：</span>拥有多年的项目开发经验和丰富的授课经验，曾在金山和人人网等知名企业任职。主导开发过多个企业重大的项目。常以风趣，幽默的语言活跃课堂气氛。授课中，让学生掌握思想，因为代码仅仅是思想的一种表现形式。以贴切的教学案例及代码示范，让学生轻易掌握知识点并能灵活运用。另外，经常通过讲述自己工作中的小故事来传授学生一些实际工作中的经验，让学生们了解职场以及求职面试的技巧。",
                    video:""
                }

            ],
            [//ad4
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/wangguoying.jpg",
                    dis:"display:block",
                    teacher:"王老师",
                    require:"<span>讲师语录：</span>机会永远是为有准备的人准备的，加油吧！",
                    introduction:"<span>个人简介：</span>近10年工作经验,从事IT教育6年。精通C/C++，Java，MySQL，Oracle，JSP，Servlet等编程语言和数据库系统，对流行框架Struts2，Hibernate，Spring深入的研究，在数据库的设计及Java流行框架的使用上有很丰富的开发经验,曾主导开发过《校园一卡通管理平台》，某培训机构教学管理系统、OA办公自动化系统等；对Android系统及其开发技术有一定研究和见解；能根据学生实际需求设置授课内容，授课重点突出，思路清晰，深入浅出，善于从生活中提取案例，对于复杂的知识点，能够总结其规律性，便于学生理解和记忆。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/yangjingwen.jpg",
                    dis:"display:block",
                    teacher:"杨老师",
                    require:"<span>讲师语录：</span>学习是痛苦的，既然选择，便只顾风雨兼程。",
                    introduction:"<span>个人简介：</span>蔻丁武汉校区Android教学主管。具有3年JavaEE全栈开发经验、5年Android开发经验，曾主导和参与研发的项目有中国电信政企经理门户系统、实名登记系统、天翼好吃佬系统、天翼金融系统、华为手机P2系统级应用等，并有多款APP发布在应用市场。授课思路清晰、严谨、深入浅出、注重细节，以实际开发场景作为教学案例，注重提升学生解决问题的能力和自学能力。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/ad_prc8.jpg",
                    dis:"display:none",
                    teacher:"邱老师",
                    require:"<span>讲师语录：</span>你可以这样理解impossible——I’m possible！",
                    introduction:"<span>个人简介：</span>蔻丁教育大连校区Android高级讲师，拥有多年JavaEE项目开发经验及Android开发经验。常以风趣、幽默的语言活跃课堂气氛，能记住每位学员的优点和缺点，因材施教。授课思路清晰，以贴切的教学案例及代码示范，让学生轻松掌握知识点并能够灵活应用。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/ad_prc8.jpg",
                    dis:"display:none",
                    teacher:"邱老师",
                    require:"<span>讲师语录：</span>你可以这样理解impossible——I’m possible！",
                    introduction:"<span>个人简介：</span>蔻丁教育大连校区Android高级讲师，拥有多年JavaEE项目开发经验及Android开发经验。常以风趣、幽默的语言活跃课堂气氛，能记住每位学员的优点和缺点，因材施教。授课思路清晰，以贴切的教学案例及代码示范，让学生轻松掌握知识点并能够灵活应用。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/ad_prc8.jpg",
                    dis:"display:none",
                    teacher:"邱老师",
                    require:"<span>讲师语录：</span>你可以这样理解impossible——I’m possible！",
                    introduction:"<span>个人简介：</span>蔻丁教育大连校区Android高级讲师，拥有多年JavaEE项目开发经验及Android开发经验。常以风趣、幽默的语言活跃课堂气氛，能记住每位学员的优点和缺点，因材施教。授课思路清晰，以贴切的教学案例及代码示范，让学生轻松掌握知识点并能够灵活应用。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/ad_prc8.jpg",
                    dis:"display:none",
                    teacher:"邱老师",
                    require:"<span>讲师语录：</span>你可以这样理解impossible——I’m possible！",
                    introduction:"<span>个人简介：</span>蔻丁教育大连校区Android高级讲师，拥有多年JavaEE项目开发经验及Android开发经验。常以风趣、幽默的语言活跃课堂气氛，能记住每位学员的优点和缺点，因材施教。授课思路清晰，以贴切的教学案例及代码示范，让学生轻松掌握知识点并能够灵活应用。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/ad_prc8.jpg",
                    dis:"display:none",
                    teacher:"邱老师",
                    require:"<span>讲师语录：</span>你可以这样理解impossible——I’m possible！",
                    introduction:"<span>个人简介：</span>蔻丁教育大连校区Android高级讲师，拥有多年JavaEE项目开发经验及Android开发经验。常以风趣、幽默的语言活跃课堂气氛，能记住每位学员的优点和缺点，因材施教。授课思路清晰，以贴切的教学案例及代码示范，让学生轻松掌握知识点并能够灵活应用。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/ad_prc8.jpg",
                    dis:"display:none",
                    teacher:"邱老师",
                    require:"<span>讲师语录：</span>你可以这样理解impossible——I’m possible！",
                    introduction:"<span>个人简介：</span>蔻丁教育大连校区Android高级讲师，拥有多年JavaEE项目开发经验及Android开发经验。常以风趣、幽默的语言活跃课堂气氛，能记住每位学员的优点和缺点，因材施教。授课思路清晰，以贴切的教学案例及代码示范，让学生轻松掌握知识点并能够灵活应用。",
                    video:""
                }

            ]],
            [[//HTML51
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/wangmingyue.jpg",
                    dis:"display:block",
                    teacher:"王老师",
                    require:"<span>讲师语录：</span>教育的唯一工作与全部工作可以总结在这一概念之中——道德！",
                    introduction:"<span>个人简介：</span>蔻丁HTML5教学总监，蔲丁UI教学总监，蔲丁北科校区校长。原中科院计算所专家，曾任北京市高校师资培训中心特邀讲师,多年担任北京市属高校师资培训工作。11年的UI、WEB前端开发教育培训经验，4年HTML5开发经验，深刻理解教学研究、教学管理工作,热爱教育事业。精通HTML5.0及CSS3.0、JavaScript等前端技术，授课通俗易懂，注重学员学习体验，多次获得教学效果方面奖励，崇尚化繁为简，快乐学习，快乐成功的教学方式。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/dupeng.jpg",
                    dis:"display:block",
                    teacher:"杜老师",
                    require:"<span>讲师语录：</span>用良心做教育，成就您的梦想！",
                    introduction:"<span>个人简介：</span>拥有10年WEB前端开发经验，6年教学经验。高级讲师，HTML5梦工厂特约讲师，是中国首批从事教育培训的HTML5讲师，开发过日均千万的PV项目。曾被邀请录讲名师课程，录有：《逐行分析jquery源码的奥秘》《AngularJs视频教程》《bootstrap视频教程》《HTML5系列教程》《移动端及微信场景实战》等，录讲课程深受好评。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/quanzhansheng.jpg",
                    dis:"display:block",
                    teacher:"全老师",
                    require:"<span>讲师语录：</span>不为输赢，只是认真！",
                    introduction:"<span>个人简介：</span>拥有11年的软件开发经验，全栈工程师，资深项目经理，WEB技术专家；精通JAVA，HTML5，C#，PHP，Oracle，Mysql，Sqlserver，Salesforce等技术，曾参与东芝、每日新闻、罗氏制药、丰田、NHK等多家大型企业系统的设计开发工作，在企业信息化系统，云计算，HTML5混合开发等方面拥有丰富的实战经验，并持有SCJP，PMP，Salesforce（DEV401）认证。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/haohonglin.jpg",
                    dis:"display:block",
                    teacher:"郝老师",
                    require:"<span>讲师语录：</span>人所缺乏的不是才干而是志向，不是成功的能力而是勤劳的意志！",
                    introduction:"<span>个人简介：</span>蔻丁HTML5学科高级讲师，3年软件开发经验，2012年开始从事手机移动端的开发。同时负责过多个web端与移动端的项目开发，有着丰富经验的项目开发经验，授课风趣幽默，注重理论基础与实际项目相结合，善于对技术原理的讲解以及学生自学能力的培养。授课思路清晰，以贴切的教学案例及代码示范，让学生轻易掌握知识点并能灵活运用。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/wuxunxun.jpg",
                    dis:"display:block",
                    teacher:"吴老师（大勋）",
                    require:"<span>讲师语录：</span>问题是一切的源头，也是尽头，它解决不完！我们只需要找到捷径，一切即可水到渠成！",
                    introduction:"<span>个人简介：</span>蔻丁教育HTML5讲师，年轻，有活力。曾任苏州某上市公司前端项目主管，指导并开发多个电子商务平台；在教学上及时根据行业动态正确调整教学方法，使学生能够更快的和社会接轨。授课思路清晰，多角度剖析开发语言的专业知识，讲解生动活泼，激情四射，富有亲和力。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/xuliwen.jpg",
                    dis:"display:block",
                    teacher:"徐老师",
                    require:"<span>讲师语录：</span>天道酬勤，勤奋可以逆转人生！",
                    introduction:"<span>个人简介：</span>‌10年以上互联网电商，航空，金融领域工作经验；有丰富的项目管理及产品研发经验。资深电商行业分析师，全栈式系统架构师，精通 HTML5、Bootstrap、Javascript、CSS3、Angularjs、Reactjs、ObjectiveC、Swift、Android、Unity3d、Java、C#、Python。善于通过案例式讲解，培养学生的综合应用与项目整合思维能力，善于结合企业前沿技术应用到教学当中。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/liman.jpg",
                    dis:"display:block",
                    teacher:"李老师",
                    require:"<span>讲师语录：</span>每一次努力，都有一份收获，点点滴滴，成就真正的自己！",
                    introduction:"<span>个人简介：</span>蔻丁教育HTML5讲师，4年多项目经验，有丰富的移动端WEB和App混合开发经验，扎实的前端技术功底，对移动端开发有深入的理解。授课认真负责，重视培养学生的自学能力和实际工作能力。擅长将复杂的问题剖析、细化，分模块耐心为学生讲解，可以分别从页面性能、代码可维护性和用户体验的角度分析，帮学生提升和改善代码。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/yintao.jpg",
                    dis:"display:block",
                    teacher:"尹老师",
                    require:"<span>讲师语录：</span>记不住，是因为练习的还不够多！",
                    introduction:"<span>个人简介：</span>从事5年的JavaWeb开发，有3年的互联网平台研发经验，2011年参与开发了大型海运电子商务平台。担任过程序员，产品设计，teamleader，2015年参与开发了ifootball安卓端社交APP。3年的教学工作经验。授课方式，深入浅出，善于讲解复杂的概念，严谨的编程风格，能让学生掌握最规范的开发方式。",
                    video:""
                }
            ],
            [//HTML52
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/maxiaoxin.jpg",
                    dis:"display:block",
                    teacher:"马老师",
                    require:"<span>讲师语录：</span>如果你知道去哪，全世界都会为你让路！",
                    introduction:"<span>个人简介：</span>蔻丁移动前端开发（HTML5）专业讲师，7年前端及移动端开发实践经验。曾参与负责多个大型项目的前端开发，在多年的实践中总结了实际工作中所需要的技能及技巧，对待教学认真负责，平易近人，细心辅导，不厌其烦，讲课内容深入浅出，擅长调动课堂气氛。在教学中经常拓展实际工作中经验，分享并传授给学生，能让学生很快的将所学知识应用到实际项目中。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/chenyanqiu.jpg",
                    dis:"display:block",
                    teacher:"陈老师（Cherry）",
                    require:"<span>讲师语录：</span>生命可以随心所欲，但不能随波逐流！",
                    introduction:"<span>个人简介：</span>蔻丁HTML5讲师，性格开朗，为人细心，做事认真，有较强的责任心，多年的前端项目开发经验。常以幽默的语言活跃课堂气氛。授课思路清晰，以贴切的案例，形象的演示一些难以理解的内容，让学员轻易掌握知识点并能深刻的理解和运用。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/shaoyizhi.jpg",
                    dis:"display:block",
                    teacher:"邵老师",
                    require:"<span>讲师语录：</span>千里之行始于足下，不积跬步无以至千里！",
                    introduction:"<span>个人简介：</span>蔻丁HTML5学科高级讲师，三年多web前端开发经验，熟练使用HTML5，jquery，CSS3，js等技术开发多个web和移动端App应用，曾在IBM中国和网易等资深互联网公司任职，并且担任前端的team leader ，负责搭建web前端架构，考虑前端技术选型，带领过三十人左右的团队完成项目，主要涉足媒体，银行，电子商务，P2P，O2O等不同行业，熟练各行业web开发的特点和需求以及对应的业务。熟练使用原生Js，CSS3，bootstrap，swiper，angularJs ，jquerymobile，jqueryUI等技术,在教育领域也有丰富经验，参与过html课程体系的编写。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/wangyuejiao.jpg",
                    dis:"display:block",
                    teacher:"王老师",
                    require:"<span>讲师语录：</span>勇敢去闯，万一你成功了，自己会很开心，即使你失败了，也能让别人开心！",
                    introduction:"<span>个人简介：</span>三年多工作经验，专注于WEB前端静态页面与动态效果开发，熟练使用WEB前端技术，CSS3,HTML5, jQuery,原生js等基本技术;对jQuery Mobile, jQuery UI , jQuery EasyUI等流行前端框架的实现原理有深入研究，并且能自定义实现。曾参与多个类型项目的开发，如电商类、管理系统类、社区类等，在项目中主要负责项目概要设计、UI原型设计、考虑如何提高软件体验度、前端架构的搭建、自定义组件的编写，并且让WEB端的内容与后端实现，功能集成与交互。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/yangguang.jpg",
                    dis:"display:block",
                    teacher:"杨老师",
                    require:"<span>讲师语录：</span>做有意义的事情！",
                    introduction:"<span>个人简介：</span>以风趣，幽默的授课方式深受学生喜爱，善于活跃课堂气氛，能记住学生身上的优点与喜好，因材施教，与学生打成一片，对待学生的问题能够及时解答，对待教学有充足的耐心和责任感，注重理论基础和实际项目相结合，以实际工作需求带动学生的学习氛围和兴趣，让学生全面了解技术的原理和使用思想。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/luweifeng.jpg",
                    dis:"display:block",
                    teacher:"陆老师",
                    require:"<span>讲师语录：</span>想要超神就要努力 在现实中超神永远大于在游戏中超神！",
                    introduction:"<span>个人简介：</span>蔻丁HTML5学科高级讲师，具有4年多嵌入式和交互式研发经验，在HTML/CSS开发和教学方面造诣精湛，在大型网站架构方面有着丰富的经验。授课风格风趣幽默，深入浅出，实战性极强，深受学生欢迎，对jQuery的特点把控精确到位，风格独特。被学生们亲切地称为“代码男神”。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/xiejinrong.jpg",
                    dis:"display:block",
                    teacher:"谢老师",
                    require:"<span>讲师语录：</span>结果固然重要，但享受过程往往更能让人有成就感！",
                    introduction:"<span>个人简介：</span>10多年WEB前端开发经验，精通HTML5,CSS3, JavaScript等前端技术，开发过大型BS ERP系统、电商网购物系统，保险系统等项目。曾任职UI设计师、高级WEB前端开发工程师、 Team Leader等职位，对WEB前端一些前沿技术有深入研究，教学风格通俗易懂、有亲和力，并善于从思路上引导学生自主解决问题，注重理论与实际项目相结合、让学生更快的了解和适应企业级项目开发。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/h5_prc5.jpg",
                    dis:"display:block",
                    teacher:"李老师",
                    require:"<span>讲师语录：</span>每一发奋努力的背后，必有加倍的赏赐！",
                    introduction:"<span>个人简介：</span>三年多工作经验，同时负责过多个web端与移动端的项目开发，有着丰富的项目开发经验，专注于WEB前端静态页面与动态效果开发，熟练使用WEB前端技术，CSS3,HTML5, jQuery,原生js等基本技术;性格开朗，为人细心，有较强的责任心，。常以幽默的语言活跃课堂气氛。授课亲切自然,思路清晰，以贴切的案例，形象的演示一些难以理解的内容，让学员轻易掌握知识点并能深刻的理解和运用。",
                    video:""
                }
            ],
            [//HTML53
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/h5_prc6.jpg",
                    dis:"display:block",
                    teacher:"李老师",
                    require:"<span>讲师语录：</span>只有经历最痛苦的坚持，才能配的上最永久的幸福！",
                    introduction:"<span>个人简介：</span>蔻丁HTML5前端讲师，曾负责参与多个大型金融和门户类型项目的前端和移动端开发，崇尚风趣幽默的教学，授课思路清晰细致，课下辅导练习亲切随和，乐于助人的性格给了学员很大的鼓舞和信心，本人也是一个外表呆萌，憨厚可爱，对待任何人和事都认真负责的人。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/h5_prc7.jpg",
                    dis:"display:block",
                    teacher:"刘老师",
                    require:"<span>讲师语录：</span>没有一步登天，没有功德圆满！",
                    introduction:"<span>个人简介：</span>前IBM高级软件工程师， 5年研发经验，获得IBM WORKLIGHT 跨平台移动应用高级开发者认证，致力于HTML5，Android，ios，混合应用的开发与最佳实践。为企业内部进行跨平台应用开发培训，帮助职员短时间内，高效率，快速实现技术积累与储备。热爱IT培训行业，注重理论基础与实战相结合，善于讲解技术原理以及帮助学生提高自学能力。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/h5_prc9.jpg",
                    dis:"display:block",
                    teacher:"王老师",
                    require:"",
                    introduction:"<span>个人简介：</span>蔻丁Html5讲师，10多年互联网前端开发经验，推广并引导国内使用div+css技术架构网站的先驱者之一，曾参与中宣部华人天下、东华美钻、中山公园玫瑰坊、馨亭乔德、嘉德在线等各种类型网站项目与企划，项目经验丰富，技术扎实。为人亲切、平易近人，性格幽默、开朗大方，授课思路清晰、形象生动，善于举例，使抽象的知识形象化，便于学生的理解与识记，课后积极辅导，对学生认真负责有耐心，深受学生喜爱。",
                    video:""
                },
                {
                     img:"http://www.mobiletrain.org/teacher/img/teacher/h5_prc10.jpg",
                     dis:"display:block",
                     teacher:"王老师",
                     require:"<span>讲师语录：</span>好多人做不好自己，是因为总想着做别人！",
                     introduction:"<span>个人简介：</span>蔻丁HTML5讲师，三年多web前端开发经验，曾负责某医疗公司官方网站建设、移动产品的开发，以及fis前端工程化构建。课堂经常以实用的项目实例教授给学生，理论基础与实际项目相结合，讲课幽默，耐心细致解答学生疑问，和学生打成一片，深受学生欢迎。",
                    video:""
                 },
                 {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/h5_prc11.jpg",
                    dis:"display:block",
                    teacher:"王老师",
                    require:"<span>讲师语录：</span>能培养独创性和唤起对知识愉悦的，是教师的最高本领！",
                    introduction:"<span>个人简介：</span>‌拥有10多年开发经验，曾开发过联想BDC项目管理系统，开发过联发科板卡检测系统，曾为美国mentor公司编写过中文版HyperLynxDRC的开发教程，精通javascript、dotnet、tsql、asp、vb等技术。授课方式由浅入深，思路通俗易懂，代码编写规范，尤擅长讲解学习方法，使学生掌握其知识，并能够灵活运用。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/h5_prc13.jpg",
                    dis:"display:block",
                    teacher:"吴老师",
                    require:"<span>讲师语录：</span>明天的你一定会感激今天努力的自己！",
                    introduction:"<span>个人简介：</span>五年多的前端开发经验。曾参与过多家大型网站开发；讲课幽默风趣，让人印象深刻，经常会给学生一些工作中的建议，并时常告诫学生需要培养自主学习，发现问题，解决问题的能力，从而提高学生的自主能动性。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/h5_prc16.jpg",
                    dis:"display:block",
                    teacher:"杨老师",
                    require:"<span>讲师语录：</span>没有一个知识点是不能通过“敲”解决的！",
                    introduction:"<span>个人简介：</span>蔻丁教育HTML5讲师，幽默、风趣。人送外号蛋糕老师。曾就职于成都某优秀互联网公司移动端leader。<br />2年J2EE后台开发经验，4年H5移动端开发经验，曾构建过过亿PV的移动端（微信端）火车票抢票系统，实践经验丰富！<br />善于引导学生自行解决Bug，并做出总结。",
                    video:""
                },
                {
                     img:"http://www.mobiletrain.org/teacher/img/teacher/h5_prc18.jpg",
                     dis:"display:block",
                     teacher:"张老师（Michael）",
                     require:"",
                     introduction:"<span>个人简介：</span>蔻丁教学部H5讲师。近十年IT培训从业经验。长期从事移动互联网开发相关课程的教学工作，C语言、JavaScript、ActionScript等游戏开发，从事网络CCNA、CCNP的教学、微软2000/2003/2008的系统管理、服务、AD（active directory）的教学，具有丰富的教学经验，深厚的知识功底，严谨的教学态度，磁性的声音把您带入移动互联网开发的知识殿堂；授课幽默风趣、精炼严谨，为学员掌握开发语言到项目实战提供强有力的保障。",
                    video:""
                 }
            ],[//HTML54
                 {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/h5_prc19.jpg",
                    dis:"display:block",
                    teacher:"周老师",
                    require:"<span>讲师语录：</span>一个从来没有失败过的人，必然是一个从未尝试过什么的人。",
                    introduction:"<span>个人简介：</span>‌拥有5年的开发经验，对前端开发有深入的研究，有着支付宝、网易等知名企业做前端高级开发工程师一职。善于学习，对现阶段的前端主流技术比较全面的掌握，对学生认真负责，注重学生遇到问题解决问题能力的培养，善于引导学生自主思考，本着良心教育的态度对待每一个学生。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/h5_prc20.jpg",
                    dis:"display:block",
                    teacher:"潘老师",
                    require:"",
                    introduction:"<span>个人简介：</span>4年多web前端开发经验，参与有政府OA系统的开发与维护，数字化城镇项目的开发、实施维护，响应式网站的web前端的互联网平台的开发，曾在某大型公司参与开发国外一大型响应式电商网站的开发，有丰富的web开发经验，授课注重原理的讲解和案例的练习，培养学生的动手能力，注重培养学生的编程思路的养成，使学生掌握知识点的同时能做到知识点在案例中的灵活运用。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/h5_prc21.jpg",
                    dis:"display:block",
                    teacher:"崔老师",
                    require:"<span>讲师语录：</span>授人以鱼，不如授人以渔！",
                    introduction:"<span>个人简介：</span>蔻丁教育大连校区HTML5高级讲师，10年软件开发经验，5年HTML5软件开发经验。曾担任名企team leader、项目技术负责人，负责产品架构设计和原型开发；曾多次前往日本、美国参与大型项目的设计与开发，负责部门HTML5方向新员工技术培训。授课内容均以项目开发角度进行知识点讲解，注重学员团队意识的培养，注重编码规则，代码“洁癖”，对编码方面要求严格。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/h5_prc23.jpg",
                    dis:"display:block",
                    teacher:"寅老师",
                    require:"<span>讲师语录：</span>stay hungry ,stay young！",
                    introduction:"<span>个人简介：</span>4年前端开发经验，热爱前端开发，对新技术保持高度持求知欲，为开发而生。曾同时负责多个web端与移动端的项目开发，项目开发经验丰富。擅长逻辑性思考，对移动端开发、移动端性能优化，有独到见解。为人开朗，有耐心，授课认真，注重培养学生扎实的基本工和实际开发能力，乐于帮助学生解决技术上的“疑难杂症”。",
                    video:""
                }
                ,
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/guoliting.jpg",
                    dis:"display:block",
                    teacher:"郭老师",
                    require:"<span>讲师语录：</span>业精于勤，而荒于嬉；行成于思，而毁于随。！",
                    introduction:"<span>个人简介：</span>一直从事web前端整站开发，php编程工作，之后进入教育行业已经历了三年的教学工作，所授课程包括html+css网站建设、html5架构、seo搜索引擎优化、mysql数据库、php网站系统二次开发、以及php+mysql+cms整站搭建；现在蔲丁讲授html+css课程；授课方式轻松幽默，亲和力极强，课堂上激情洋溢，声音洪亮更是亮点，堪比教学行业上的海豚音；注重理论基础与动手实践的结合，善于调动课堂积极性，增强学员的学习兴趣，对于学生始终有问必答，对教学事业一直怀有浓厚热情，一直认为教学就是教与学的过程，不但是教学生去学更要引导学生去学，在教学过程中自身也要不断去学；希望给每一位选择web前端的同学都能创造一个轻松的开始！",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/lanshigui.jpg",
                    dis:"display:block",
                    teacher:"蓝老师",
                    require:"<span>讲师语录：</span>做web时代的推动者！",
                    introduction:"<span>个人简介：</span>7年web前端开发经验，精通html5、css3、javascript等前端技术，开发过大型BS ERP系统、电商购物系统、国内外大型房地产系统、各类财务系统和各种类型的WebApp、微信公众号等。教学风格通俗易懂，有亲和力，并善于从思路上引导学生自主解决问题，注重理论与实际项目结合，让学生更快地了解和适应真正的项目开发。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/leidecheng.jpg",
                    dis:"display:block",
                    teacher:"雷老师",
                    require:"<span>讲师语录：</span>听不懂 是我没有教好，听懂而不练 下个班再见 ！",
                    introduction:"<span>个人简介：</span>蔻丁武汉校区HTML5教学主管。从业五年有余，2011开始从事前端工作，完成万科汇 ，新地置业，太湖流域水纹分析，海峡导报app，社交旅游app趣玩客若干前端项目，并且精通c#、java、golang后端语言，mssql、mysql数据库开发，并完成hrelite、hrelite2若干个香港汇丰、友邦强积金管理系统。 教学以激情著称，授课幽默风趣。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/liufeiyang.jpg",
                    dis:"display:block",
                    teacher:"刘老师",
                    require:"<span>讲师语录：</span>现在努力所经历的苦难，未来的你都会笑着说起！",
                    introduction:"<span>个人简介：</span>5年软件开发经验，2年教学经验,还有超过30款APP的开发上架经验。曾经上架的项目包括：卡拉拉学乐园，掌上联教等。以授课讲解详细，思路清晰著称，深受广大学员的喜爱。授课认真负责，幽默风趣，深受学员好评，被学员赋予“大飞哥”称号。所带毕业学生有多位都在名企工作，切实履行凭良心做教育的理念。",
                    video:""
                }
            ],[//HTML55
                 {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/sunjiaheng.jpg",
                    dis:"display:block",
                    teacher:"孙老师",
                    require:"<span>讲师语录：</span>今天在努力，明天才不会担忧。",
                    introduction:"<span>个人简介：</span>‌蔻丁教育大连校区HTML5项目经理。实战经验丰富，项目“活宝典”。对学员在学习过程中有可能会出现的问题了如指掌，能有效帮助学员规避和解决常见问题。精通PS，php，js等。热爱IT培训，喜欢与学员共同分享技术知识，帮助学员提高技术水平。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/wumingfu.jpg",
                    dis:"display:block",
                    teacher:"吴老师",
                    require:"",
                    introduction:"<span>个人简介：</span>蔻丁HTML5讲师，高级软件开发工程师。负责过多个企业级WEB项目架构及开发，有着丰富的JavaEE项目开发经验与WEB开发经验。七年多的IT培训从业经验，授课经验丰富，思路清晰，富有激情，对技术知识点的讲解层次由浅入深，通过日常生活示例引发学员思考，使得各知识点通俗易懂，注重理论联系实际，以实际项目驱动理论知识点的学习。因材施教，注重培养学员学习能力、独立思考与解决问题的能力、团队合作的能力，为学员能够顺利就业引路导航。 ",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/xiedong.jpg",
                    dis:"display:block",
                    teacher:"谢老师",
                    require:"<span>讲师语录：</span>一个人能承担多大责任，解决多少问题，决定了他的江湖地位。",
                    introduction:"<span>个人简介：</span>多年J2EE开发和WEB前端开发经验，熟练JAVA底层技术和JAVA主流框架，曾参与多个JAVA项目的开发，主要包括军工，航天，企业ERP等应用；使用H5，CSS3，Js等技术开发多个WEB应用，曾担任Delta公司前端技术顾问，搭建WEB前端架构，调节WEB架构性能，独自带领团队完成项目，主要包括云计算，智能工厂，物联网方面，农业生产方面的应用。熟练Js，CSS3，bootstrap，react，reactnative，angularJs ，jquery，jqueryUI，H5等技术，丰富的项目经验。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/yaojialong.jpg",
                    dis:"display:block",
                    teacher:"姚老师",
                    require:"<span>讲师语录：</span>看代码一千次,不如去动手敲一次，好的编程从实践开始！",
                    introduction:"<span>个人简介：</span>精通html5,css3,javascript等前端技术,曾任华兴银行，澳洲XKB工程师。合作开发过大型电商和银行系统项目，常年活跃于国内外开源社区和论坛，参加开发过的线上项目包括现华兴银行官网，Kingold官网，Meilidoor Webapp等。对后端CMS和API接口开发同样有深厚项目的经验，授课幽默风趣，耐心细致，深入浅出，实战性极强，深受学生欢迎，是学员评价最高讲师之一。",
                    video:""
                }
                ,
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/zhushengwen.jpg",
                    dis:"display:block",
                    teacher:"朱老师",
                    require:"<span>讲师语录：</span>让你玩着就把习给学了。",
                    introduction:"<span>个人简介：</span>蔻丁HTML5讲师,拥有6年工作经验,2年海外开发经验.兼具界面设计能力.拥有超强页面表现力.无论是新颖的布局结构,还是炫酷的动画效果,都能完美实现.授课耐心细致,扩展性强,对于项目开发过程中用到的相应技术,开发技巧.知无不言,言无不尽.致力于让学生毕业就能熟练上手项目开发。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/zuokeliang.jpg",
                    dis:"display:block",
                    teacher:"左老师",
                    require:"<span>讲师语录：</span>怀着一颗感恩的心去教导每一位学生，让每一个学生以感恩的心去回报社会。",
                    introduction:"<span>个人简介：</span>4年前端开发经验，热爱前端开发，对新技术保持高度持求知欲，为开发而生。曾同时负责多个web端与移动端的项目开发，项目开发经验丰富。擅长逻辑性思考，对移动端开发、移动端性能优化，有独到见解。为人开朗，有耐心，授课认真，注重培养学生扎实的基本工和实际开发能力，乐于帮助学生解决技术上的“疑难杂症”。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/h5_t173201.jpg",
                    dis:"display:block",
                    teacher:"田老师",
                    require:"<span>讲师语录：</span>做最好的自己，做有意义的人，做对别人有帮助的人",
                    introduction:"<span>个人简介：</span>12年软件开发及项目管理经验，5年教学经验，曾在秦川发展，在中国电信等上市公司历任程序员、需求分析师、项目经理及技术总监等职务，主持并参与北京电力局巡检系统、中石化进销存系统、河北供电局OA，电力客服系统及电力线路走径图等大型项目的开发，擅长javaWeb全栈开发， C/C++体系等技术，涉猎技术广泛，接触的编程语言多！讲课思路清晰，授课诙谐幽默，总能把程序中难以理解的概念用生活中的例子进行讲解，通俗易懂。擅长调动班级气氛，提高学生的学习积极性，让学员在轻松、活跃的气氛中学习！",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/h5_prc23.jpg",
                    dis:"display:none",
                    teacher:"寅老师",
                    require:"<span>讲师语录：</span>stay hungry ,stay young！",
                    introduction:"<span>个人简介：</span>4年前端开发经验，热爱前端开发，对新技术保持高度持求知欲，为开发而生。曾同时负责多个web端与移动端的项目开发，项目开发经验丰富。擅长逻辑性思考，对移动端开发、移动端性能优化，有独到见解。为人开朗，有耐心，授课认真，注重培养学生扎实的基本工和实际开发能力，乐于帮助学生解决技术上的“疑难杂症”。",
                    video:""
                }
            ]],
            [[//ui1
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/wangmingyue.jpg",
                    dis:"display:block",
                    teacher:"王老师",
                    require:"<span>讲师语录：</span>教育的唯一工作与全部工作可以总结在这一概念之中——道德！",
                    introduction:"<span>个人简介：</span>蔻丁HTML5教学总监，蔲丁UI教学总监，蔻丁北科校区校长。原中科院计算所专家，曾任北京市高校师资培训中心特邀讲师,多年担任北京市属高校师资培训工作。11年的UI、WEB前端开发教育培训经验，4年HTML5开发经验，深刻理解教学研究、教学管理工作,热爱教育事业。精通HTML5.0及CSS3.0、JavaScript等前端技术，授课通俗易懂，注重学员学习体验，多次获得教学效果方面奖励，崇尚化繁为简，快乐学习，快乐成功的教学方式。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/sunwei.jpg",
                    dis:"display:block",
                    teacher:"孙老师",
                    require:"<span>讲师语录：</span>不为失败找借口，只为成功找方法！",
                    introduction:"<span>个人简介：</span>拥有多年网页设计相关专业授课经验，曾为世界500强SK集团，中国联通，中国平安等多家企业进行过网站和软件登录界面设计，及APP界面设计等；从业多年拥有与多家设计公司保持良好的合作关系，在授课过程中会实时提供给学员最新的项目案例，让学员与企业之间完美结合；授课思路清晰，方法简单易懂，以生活中常见的事物为教学内容，给学员营造轻松易懂的学习氛围；注重对学员的能力培养，深受学员好评。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/liuchunmei.jpg",
                    dis:"display:block",
                    teacher:"刘老师",
                    require:"<span>讲师语录：</span>聪明出于勤奋，天才在于积累！",
                    introduction:"<span>个人简介：</span>多年的设计从业积累了大量工作经验，从事内容包括：商业广告、电商网站、互联网门户、专题、企业品牌、移动APP等；对互联网、手机移动端、软件行业有执着的追求与探索。精通Photoshop， 授课经验丰富，在多年与众多学员交流中逐渐理解到每个人的设计感是天生的，但是如何合理得当运用这种感觉，则需要通过讲师不断学引导和调整。从而研究出一套独特的教学方法，授课思路清晰，深入浅出，细致透彻。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/weiran.jpg",
                    dis:"display:block",
                    teacher:"魏老师",
                    require:"<span>讲师语录：</span>师者，所以传道受业解惑也！",
                    introduction:"<span>个人简介：</span>精通Ps、Ai、Axure等设计与交互软件。擅长字体/商标/Vi/海报等设计，主要从事网页UI设计、品牌VI设计及推广、平面广告、设计培训等，有丰富的电商设计、WebUI、移动端UI、软件UI、图标设计经验。实战经验丰富，讲课通俗易懂；授课风趣幽默，知识点讲解详细、深入。实战式教学，一切教学从工作出发，对UI设计，网站设计、平面印刷广告 包装设计，VI设计等有着深刻的研究。对待学生认真耐心,授课风格调理清晰，深入浅出。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/t_ui05.jpg",
                    dis:"display:block",
                    teacher:"王老师",
                    require:"<span>讲师语录：</span>当才华撑不起野心，那就静下心来学习！",
                    introduction:"<span>个人简介：</span>5年UI设计、平面设计、网页设计经验，精通Photoshop、AI、Sketck、Flinto、CorelDRAW、Axure、墨刀等UI设计相关软件。在UI设计、网页设计、交互设计方面实战经验丰富，参与多家企业网站界面设计、手机端web页面的整体UI设计，APP界面等设计工作，熟悉移动终端、网站产品构建过程，熟知行业内专业知识和产品规范，对设计有自我理解与思考。授课风格生动幽默，善于将流行互联网内容融入课程，使枯燥无味的理论知识变成学生感兴趣的“笑点”。主张从规划、设计与管理角度引导学员参与项目工作，培养学员的总体项目管理与设计思维。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/xiedong.jpg",
                    dis:"display:none",
                    teacher:"谢老师",
                    require:"<span>讲师语录：</span>一个人能承担多大责任，解决多少问题，决定了他的江湖地位！",
                    introduction:"<span>个人简介：</span>多年J2EE开发和WEB前端开发经验，熟练JAVA底层技术和JAVA主流框架，曾参与多个JAVA项目的开发，主要包括军工，航天，企业ERP等应用；使用HTML5，CSS3，Js等技术开发多个WEB应用，曾担任Delta公司前端技术顾问，搭建WEB前端架构，调节WEB架构性能，独自带领团队完成项目，主要包括云计算，智能工厂，物联网方面，农业生产方面的应用。熟练Js，CSS3，bootstrap，react，reactnative，angularJs ，jquery，jqueryUI，HTML5等技术，丰富的项目经验。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/xiedong.jpg",
                    dis:"display:none",
                    teacher:"谢老师",
                    require:"<span>讲师语录：</span>一个人能承担多大责任，解决多少问题，决定了他的江湖地位！",
                    introduction:"<span>个人简介：</span>多年J2EE开发和WEB前端开发经验，熟练JAVA底层技术和JAVA主流框架，曾参与多个JAVA项目的开发，主要包括军工，航天，企业ERP等应用；使用HTML5，CSS3，Js等技术开发多个WEB应用，曾担任Delta公司前端技术顾问，搭建WEB前端架构，调节WEB架构性能，独自带领团队完成项目，主要包括云计算，智能工厂，物联网方面，农业生产方面的应用。熟练Js，CSS3，bootstrap，react，reactnative，angularJs ，jquery，jqueryUI，HTML5等技术，丰富的项目经验。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/xiedong.jpg",
                    dis:"display:none",
                    teacher:"谢老师",
                    require:"<span>讲师语录：</span>一个人能承担多大责任，解决多少问题，决定了他的江湖地位！",
                    introduction:"<span>个人简介：</span>多年J2EE开发和WEB前端开发经验，熟练JAVA底层技术和JAVA主流框架，曾参与多个JAVA项目的开发，主要包括军工，航天，企业ERP等应用；使用HTML5，CSS3，Js等技术开发多个WEB应用，曾担任Delta公司前端技术顾问，搭建WEB前端架构，调节WEB架构性能，独自带领团队完成项目，主要包括云计算，智能工厂，物联网方面，农业生产方面的应用。熟练Js，CSS3，bootstrap，react，reactnative，angularJs ，jquery，jqueryUI，HTML5等技术，丰富的项目经验。",
                    video:""
                }
            ]],
            [[//php1
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/liwenkai.jpg",
                    dis:"display:block",
                    teacher:"李老师",
                    require:"",
                    introduction:"<span>个人简介：</span>曾任缤纷生活首席技术官（CTO），负责过国内知名上市企业三一重工等企业级PHP培训和信息架构技术咨询，担任国内最大的新媒体内容管理系统——CmsTop产品研发部经理、必趣产品技术顾问、并担任自考在线项目总监，成功收购中国自考网并改版。<br /><span class='t_a'>成就：</span>主持完成社交平台、O2O系统、社交系统、CMS、商城和即时通信等多种不同系统的研发；在自考在线期间：实现站群架构加盟模式的在线教育系统；参与国内使用最多的PHP框架，ThinkPHP的贡献和ThinkPHP视频录制，下载量高达100万；微信公众号开发视频，高达20万的下载量；完成PHP开源书籍——<a class='t_a' href='http://phpbook.phpxy.com' target='_blank'>《七天学会PHP》</a>；完成MySQL开源书籍——<a class='t_a' href='http://mysql.phpxy.com' target='_blank'>《三天入门MySQL》</a>；负责微信多用户公众号平台引擎“微易”的开发。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/php_lizhibin.jpg",
                    dis:"display:block",
                    teacher:"李老师（斌哥）",
                    require:"<span>讲师语录：</span>人生最精彩的不是成功的那一瞬间，而是那段漆黑看不到尽头、却依然在苦苦摸索的过程。",
                    introduction:"<span>个人简介：</span>具有2年北斗算法研发经验，2年嵌入式开发经验，2年PHP开发经验，熟悉Linux操作系统以及Linux多线程、网络编程。精通PHP+Mysql编程，精通C、 swift服务端、C++等多种开发语言，精通PHP开发各种框架如Laravel、ThinkPHP、CI，精通HTML5、CSS、JavaScript前端开发，拥有3年多教学经验，授课幽默风趣、耐心细致、富有激情，对学员认真负责，能够引导学员自主学习，深受学员好评。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/php_likun.jpg",
                    dis:"display:block",
                    teacher:"李老师",
                    require:"<span>讲师语录：</span>只有你的行动，才能决定你的价值！",
                    introduction:"<span>个人简介：</span>曾任上市企业华胜天成集团PHP高级研发工程师，担任PHP研发主管职位。<br />成就：<br />多年的PHP开发经验，主导过光大银行、哈尔滨银行及中国黄金在线商城的研发。多年项目主管与教学经验。现专注PHP研发与教学工作，学生就是责任，学员未来的发展就是我最大的责任。对前端技术（JavaScript、HTML5、CSS3）有深入的研究、乐于分享，讲课幽默风趣，通俗易懂。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/php_lijie.jpg",
                    dis:"display:block",
                    teacher:"李老师（Jerry）",
                    require:"<span>讲师语录：</span>一心向着目标前进的人，全世界都会为其让路！",
                    introduction:"<span>个人简介：</span>拥有多年嵌入式、PHP开发、C语言、PHP底层、Linux、swift服务端技术、javascript、MySQL和服务器大并发等开发经验和授课经验。善于对知识归纳总结提炼，因此总能将复杂难懂的知识转换成学生容易接受的旋律。经常与学员分享开发经验以及工作中待人处事的方法，不但教会学员知识，更重要的是也教会了学员如何做人做事。学生评价其授课风格严肃而不失幽默，严谨而不失灵活，被学员赋予“杰哥”称号。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/php05.jpg",
                    dis:"display:block",
                    teacher:"褚老师",
                    require:"",
                    introduction:"<span>个人简介：</span>曾任中国经济网教育产品总监、圈课网创始人。负责过学科网直播产品研发、水晶石社会化学习平台、人人影视架构设计等。<br />成就：主导研发过社交系统、电商系统、直播系统、慕课系统、跨平台系统等。曾主导研发过国内第一个场景式动画教学系统中经幸福学院；完成人人影视千万级业务的架构支撑；创办过国内第一家在线教育科技媒体网站，成为国内在线教育行业第一批推动者。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/php_t173201.jpg",
                    dis:"display:block",
                    teacher:"成老师",
                    require:"<span>讲师语录：</span>你连PHP都学不会，你还能干什么！",
                    introduction:"<span>个人简介：</span>精通php、c、c++、oc等多种语言，有多年教学经验，有丰富的项目经验。精通PHP+Mysql编程，精通PHP开发各种框架如Laravel、ThinkPHP等，精通HTML5、CSS、JavaScript前端开发。授课幽默风趣、耐心细致、富有激情，对学员认真负责，深受学员好评。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/xiedong.jpg",
                    dis:"display:none",
                    teacher:"谢老师",
                    require:"<span>讲师语录：</span>一个人能承担多大责任，解决多少问题，决定了他的江湖地位！",
                    introduction:"<span>个人简介：</span>多年J2EE开发和WEB前端开发经验，熟练JAVA底层技术和JAVA主流框架，曾参与多个JAVA项目的开发，主要包括军工，航天，企业ERP等应用；使用HTML5，CSS3，Js等技术开发多个WEB应用，曾担任Delta公司前端技术顾问，搭建WEB前端架构，调节WEB架构性能，独自带领团队完成项目，主要包括云计算，智能工厂，物联网方面，农业生产方面的应用。熟练Js，CSS3，bootstrap，react，reactnative，angularJs ，jquery，jqueryUI，HTML5等技术，丰富的项目经验。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/xiedong.jpg",
                    dis:"display:none",
                    teacher:"谢老师",
                    require:"<span>讲师语录：</span>一个人能承担多大责任，解决多少问题，决定了他的江湖地位！",
                    introduction:"<span>个人简介：</span>多年J2EE开发和WEB前端开发经验，熟练JAVA底层技术和JAVA主流框架，曾参与多个JAVA项目的开发，主要包括军工，航天，企业ERP等应用；使用HTML5，CSS3，Js等技术开发多个WEB应用，曾担任Delta公司前端技术顾问，搭建WEB前端架构，调节WEB架构性能，独自带领团队完成项目，主要包括云计算，智能工厂，物联网方面，农业生产方面的应用。熟练Js，CSS3，bootstrap，react，reactnative，angularJs ，jquery，jqueryUI，HTML5等技术，丰富的项目经验。",
                    video:""
                }
            ]],
            [[//java1
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/huangguizhao.jpg",
                    dis:"display:block",
                    teacher:"黄老师（Andy）",
                    require:"<span>讲师语录：</span>把时间浪费在美好的事物上！",
                    introduction:"<span>个人简介：</span>有多年的项目实战经验，曾在全通教育，中兴通讯等上市公司担任高级软件工程师，项目经理一职，曾主导的项目有中国移动营销管理平台，全通企业大学学习云平台，高校教学信息化管理云平台，中兴学习云平台等众多项目；现在教育培训方向也有自己的心得体会，深知学习的难度曲线，注重学员学习引导，倡导实战，注重学员理论基本功的沉淀。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/wangliang.jpg",
                    dis:"display:block",
                    teacher:"王老师（亮哥）",
                    require:"<span>讲师语录：</span>心在哪里，财富就在哪里！",
                    introduction:"<span>个人简介：</span>蔻丁武汉校区教学部培训主管，从业软件行业10多年，有着丰富的前端、后端开发和管理经验。参与过华为和IBM联合项目MEAP的开发，中南财经政法大学的机房管理系统开发、东风雪铁龙多个企业项目开发、龙工、三一重工、安琪等多个大型企业的项目开发，能为学员项目实战提供丰富的经验。5年多的教学经验，授课幽默风趣，善于跟学员沟通，教授过的学员不少成功入职腾讯、百度、阿里巴巴，且均有不错的口碑。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/tianpan.jpg",
                    dis:"display:block",
                    teacher:"田老师",
                    require:"<span>讲师语录：</span>高调做事，低调做人！",
                    introduction:"<span>个人简介：</span>6年软件开发经验，2年多教学经验，主持并参与青海翔光物业管理系统、宝鸡XXXX快乐淘书项目的开发，擅长Java基础、精通My SQL及Oracle数据库的使用及调优，对JavaScript有着较长时间的深入研究，并录有网络教学视频，深受网友一致好评!<br />授课耐心细致、条理清晰、喜欢钻研、探索，随和质朴、平易近人!",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/zhengzhanpeng.jpg",
                    dis:"display:block",
                    teacher:"郑老师",
                    require:"<span>讲师语录：</span>细节决定成败, 注重每一环节！",
                    introduction:"<span>个人简介：</span>10年软件开发经验，曾先后担任国际知名IT公司的软件研发、项目规划及策划工作，主持并参与P-Gate, USonline,TPM2009等要求高、时间紧的多个大型欧美项目的开发，积累了丰富的代码编写、调试及系统级别的评估等实战经验。<br />授课有激情、关注每一环节，要求学生在开发过程中注重细节!",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/caojie.jpg",
                    dis:"display:block",
                    teacher:"曹老师",
                    require:"<span>讲师语录：</span>所谓成功就是不断失败而不丧失热情！",
                    introduction:"<span>个人简介：</span>2009~2010在华为从事U2000(统一网络管理系统)平台研发，2011~2015在NEC从事IMS-PTN网络管理系统研发，工作期间主要负责SBI（南向业务接口）、客户端在线升级、时间时钟接口，擅长Servlet编程、RMI、Socket、线程池、多任务并发等等。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/liliting.jpg",
                    dis:"display:block",
                    teacher:"李老师",
                    require:"<span>讲师语录：</span>多年后你一定会感谢现在努力的自己！",
                    introduction:"<span>个人简介：</span>蔻丁教学部Java讲师，多年软件开发经验，曾经参与中国人寿保险投保项目(PICC人寿保险)的开发工作，现此项目已经上线。有java培训从业经验，曾从事互联网开发相关课程的教学工作，具有丰富的教学经验，深厚的编程底蕴，有趣的学习氛围，洪亮的声音把您带入移动互联网开发的知识殿堂；授课由浅入深、生动实用，把生活案例引入到学习中，让枯燥的学习变成有趣的事，在愉快的氛围里学到了知识。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/wangfuqi.jpg",
                    dis:"display:block",
                    teacher:"王老师",
                    require:"",
                    introduction:"<span>个人简介：</span>多年项目实战经验，熟练掌握主流框架Spring和SpringMVC、mybatis的使用、架构、原理，Struts，hibernate架构、原理，jsp/servlet技术、JavaSE核心语法、SQL语句的书写、Oracle和MySQL的使用；熟悉HTML，DIV+CSS前台页面开发技术，javaScript、Ajax及jQuery技术并在实际项目中得到应用。曾主导的企业级项目有：人力资源管理系统、电子商务鲜花商城、银行IC卡web管理系统等。授课思路清晰，多角度剖析开发语言的专业知识，善于通过案例式讲解，培养学生的综合应用与项目整合思维能力。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/xingpenghui.jpg",
                    dis:"display:block",
                    teacher:"邢老师",
                    require:"<span>讲师语录：</span>天行健君子以自强不息，地势坤君子以厚德载物！",
                    introduction:"<span>个人简介：</span>毕业于清华大学微软全球最具价值专家，微软Tech.Ed 大会金牌讲师清华大学Oracle-java技术俱乐部，清华大学谷歌俱乐部，清华大学微软俱乐部创始人,资深软件架构师，intel软件技术专家，CSDN著名技术专家，具备多年的软件编程经验与讲师授课经历，并在人机交互，教育，信息安全，广告系统开发诸多产品，具备深厚的项目管理经验以及研发经验, 拥有两项发明专利。业界拥有极高的教学口碑与业界名声，曾带领学生微软编程大赛获得大奖。曾经先后巡讲数十所中学与高校，影响数十万人。并指导衡水中学学生获得信息学奥林匹克竞赛金牌1枚，银牌两枚，铜牌一枚，金牌获得保送清华大学计算机系的资格，银牌分别获得上海交通大学与中国科学技术大学的保送资格。",
                    video:""
                }
            ]],
            [[//大数据1
                 {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/yujiang_java.jpg",
                    dis:"display:block",
                    teacher:"于老师",
                    require:"<span>讲师语录：</span>不经历风雨怎么见彩虹，学习阿甘精神不去计较的努力，为自己的目标坚持到底，努力向前。",
                    introduction:"<span>个人简介：</span>十多年的信息化、互联网化建设、大数据系统架构及分析经验，主导过建设银行云计算平台产品研发和实施，大数据平台产品研发和实施。从世界500强企业到私人企业,并兼具甲乙方的经验，对java、Hadoop、Scala、Spark、机器学习等大数据技术具有深厚的技术功底。行业经验包括电子商务、金融 、电信、汽车等，能利用广泛的技术迅速将客户需求转化为可操作的项目计划。拥有千万级到亿万级PV网站技术架构实现经验，开发过大型的互联网B2B2C网站，如：建设银行的善融商城，长久的汽配商城千品猫等系统。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/yanghongyan_java.jpg",
                    dis:"display:block",
                    teacher:"杨老师",
                    require:"",
                    introduction:"<span>个人简介：</span>蔻丁大数据讲师，多年的软件开发经验，参与过庄络农贸通，中国农技推广中心，96168三农服务网等多个农业项目的开发。有丰富的授课经验，在北京各个知名的培训机构担任过讲师，讲课由浅入深，通俗易懂，善于活跃课堂气氛，因材施教，注重对学生能力的培养，得到学员的高度好评。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/wangquan.jpg",
                    dis:"display:none",
                    teacher:"汪老师",
                    require:"<span>讲师语录：</span>只有你的行动，才能决定你的价值！",
                    introduction:"<span>个人简介：</span>拥有多年设计从教经验，曾于知名企业及院校担任讲师，精通Photoshop、Illustrator等数字图形交互软件，对互联网行业有深入了解，参与过众多商业项目的研发工作，服务过电商、教育等行业。曾为中青旅，歌华有线，腾讯视频，东跃在线等多家知名企业打造项目视觉设计。本着以学生为本的教学理念，因人而异，因材施教，打造多元化人才。轻松愉快的上课氛围中带领大家走进UI设计神奇世界的大门。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/wangquan.jpg",
                    dis:"display:none",
                    teacher:"汪老师",
                    require:"<span>讲师语录：</span>只有你的行动，才能决定你的价值！",
                    introduction:"<span>个人简介：</span>拥有多年设计从教经验，曾于知名企业及院校担任讲师，精通Photoshop、Illustrator等数字图形交互软件，对互联网行业有深入了解，参与过众多商业项目的研发工作，服务过电商、教育等行业。曾为中青旅，歌华有线，腾讯视频，东跃在线等多家知名企业打造项目视觉设计。本着以学生为本的教学理念，因人而异，因材施教，打造多元化人才。轻松愉快的上课氛围中带领大家走进UI设计神奇世界的大门。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/liuchunmei.jpg",
                    dis:"display:none",
                    teacher:"刘老师",
                    require:"<span>讲师语录：</span>聪明出于勤奋，天才在于积累！",
                    introduction:"<span>个人简介：</span>多年的设计从业积累了大量工作经验，从事内容包括：商业广告、电商网站、互联网门户、专题、企业品牌、移动APP等；对互联网、手机移动端、软件行业有执着的追求与探索。精通Photoshop， 授课经验丰富，在多年与众多学员交流中逐渐理解到每个人的设计感是天生的，但是如何合理得当运用这种感觉，则需要通过讲师不断学引导和调整。从而研究出一套独特的教学方法，授课思路清晰，深入浅出，细致透彻。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/shaoyizhi.jpg",
                    dis:"display:none",
                    teacher:"绍老师",
                    require:"<span>讲师语录：</span>千里之行始于足下，不积跬步无以至千里！",
                    introduction:"<span>个人简介：</span>蔻丁HTML5学科高级讲师，三年多web前端开发经验，熟练使用HTML5，jquery，CSS3，js等技术开发多个web和移动端App应用，曾在IBM中国和网易等资深互联网公司任职，并且担任前端的team leader ，负责搭建web前端架构，考虑前端技术选型，带领过三十人左右的团队完成项目，主要涉足媒体，银行，电子商务，P2P，O2O等不同行业，熟练各行业web开发的特点和需求以及对应的业务。熟练使用原生Js，CSS3，bootstrap，swiper，angularJs ，jquerymobile，jqueryUI等技术,在教育领域也有丰富经验，参与过html课程体系的编写。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/wuxunxun.jpg",
                    dis:"display:none",
                    teacher:"吴老师（大勋）",
                    require:"<span>讲师语录：</span>问题是一切的源头，也是尽头，它解决不完！我们只需要找到捷径，一切即可水到渠成！",
                    introduction:"<span>个人简介：</span>蔻丁教育HTML5讲师，年轻，有活力。曾任苏州某上市公司前端项目主管，指导并开发多个电子商务平台；在教学上及时根据行业动态正确调整教学方法，使学生能够更快的和社会接轨。授课思路清晰，多角度剖析开发语言的专业知识，讲解生动活泼，激情四射，富有亲和力。",
                    video:""
                },
                {
                    img:"http://www.mobiletrain.org/teacher/img/teacher/xiedong.jpg",
                    dis:"display:none",
                    teacher:"谢老师",
                    require:"<span>讲师语录：</span>一个人能承担多大责任，解决多少问题，决定了他的江湖地位！",
                    introduction:"<span>个人简介：</span>多年J2EE开发和WEB前端开发经验，熟练JAVA底层技术和JAVA主流框架，曾参与多个JAVA项目的开发，主要包括军工，航天，企业ERP等应用；使用HTML5，CSS3，Js等技术开发多个WEB应用，曾担任Delta公司前端技术顾问，搭建WEB前端架构，调节WEB架构性能，独自带领团队完成项目，主要包括云计算，智能工厂，物联网方面，农业生产方面的应用。熟练Js，CSS3，bootstrap，react，reactnative，angularJs ，jquery，jqueryUI，HTML5等技术，丰富的项目经验。",
                    video:""
                }
            ]]

        ];
        var num=0;
        $base_ul=$(".teacher_ls_lt");

        $base_li=$baseUl;
        $list=$(".teacher_list_w").find(".teacher_list");
            $base_li.first().addClass("active");
            $base_li.each(function(index){
            $(this).click(function(){
                num=index;
                $(this).addClass("active").siblings().removeClass("active");
                $list.eq(index).show().siblings().hide();
            });

        });
        $base_ul.each(function(ul_num){
             $num=$base_ul.eq(ul_num).find(".num");
             $index=$base_ul.eq(ul_num).find(".index");
             $foot=$base_ul.eq(ul_num).find(".foot");
                        $foot.click(function(){
                         a=$(this).siblings('.num').length;
                    })
                   $img=$base_ul.eq(ul_num).find("img");
                   $li=$base_ul.eq(ul_num).find("li");
                   $dt=$base_ul.eq(ul_num).find("dt");
                   $dl=$base_ul.eq(ul_num).find("dl");
                   $dd_1=$base_ul.eq(ul_num).find(".dd_1");
                   $dd_2=$base_ul.eq(ul_num).find(".dd_2");
                   $dd_3=$base_ul.eq(ul_num).find(".dd_3");
                   for(var n=0;n<8;n++){
                      $img.eq(n).attr("src",(arr[ul_num][num][n].img));
                      $li.eq(n).attr("style",(arr[ul_num][num][n].dis));
                      $dt.eq(n).html(arr[ul_num][num][n].teacher);
                      $dd_1.eq(n).html(arr[ul_num][num][n].require);
                      $dd_2.eq(n).html(arr[ul_num][num][n].introduction);
                      $dd_3.eq(n).html(arr[ul_num][num][n].video);
                     }
             $num.each(function(num){
                function aaaa(){
                   $img=$base_ul.eq(ul_num).find("img");
                   $li=$base_ul.eq(ul_num).find("li");
                   $dt=$base_ul.eq(ul_num).find("dt");
                   $dl=$base_ul.eq(ul_num).find("dl");
                   $dd_1=$base_ul.eq(ul_num).find(".dd_1");
                   $dd_2=$base_ul.eq(ul_num).find(".dd_2");
                   $dd_3=$base_ul.eq(ul_num).find(".dd_3");
                   for(var n=0;n<8;n++){
                      $img.eq(n).attr("src",(arr[ul_num][num][n].img));
                      $li.eq(n).attr("style",(arr[ul_num][num][n].dis));
                      $dt.eq(n).html(arr[ul_num][num][n].teacher);
                      $dd_1.eq(n).html(arr[ul_num][num][n].require);
                      $dd_2.eq(n).html(arr[ul_num][num][n].introduction);
                      $dd_3.eq(n).html(arr[ul_num][num][n].video);
                     }
                   }
                $(this).click(function(){
                   $(this).addClass('active').siblings().removeClass('active');
                   num=$(this).index()-1;
                   b=$(this).siblings().length;
                   if(num==b-2){
                    $(window).scrollTop(850);
                   }
                   aaaa();
                })
                $index.click(function(){
                    $(this).siblings('.num').eq(0).addClass('active').siblings().removeClass('active');
                    num=0;
                    aaaa();
                })
                $foot.click(function(){
                    num=a-1;
                    $(window).scrollTop(850);
                    $(this).siblings('.num').eq(num).addClass('active').siblings().removeClass('active');
                    aaaa();
                })
            })
       })

});
$(function(){
    /*底部切换*/
        $(function(){
            var $botBtn,$botLi;
            $botBtn=$(".c_bot_lt_hd").find("a");
            $botLi=$(".c_bot_lt ul").find("li");
            $botBtn.first().addClass("active");
            $botLi.first().show();

            $botBtn.each(function(index){
                $(this).mouseover(function(){
                    $(this).addClass("active").siblings().removeClass("active");
                    $botLi.eq(index).show().siblings().hide();

                });
            });


        });
})